// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-api-template/controllers"
	"go-api-template/settings"
)

// Injectors from wire.go:

func InitializeApp() *App {
	appSettings := settings.NewAppSettings()
	databaseSettings := settings.NewDatabaseSettings()
	client := NewDatabase(databaseSettings)
	helloController := controllers.NewHelloController(client)
	app := NewApp(appSettings, helloController)
	return app
}
